"""VAEL rebrand guards (PR-1 foundation).

Runs under pytest AND standalone (``python3 tests/branding/test_vael_brand.py``)
so the lightweight CI job needs no dependencies.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent


def _read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


def test_license_unchanged():
    lic = _read("LICENSE")
    assert "Copyright (c) 2025 Nous Research" in lic
    assert lic.startswith("MIT License")


def test_readme_attribution():
    readme = _read("README.md")
    assert "based on hermes agent by nous research (mit" in readme.lower()
    assert any(ln.startswith("# VAEL") for ln in readme.splitlines())


def test_notice_exists():
    notice = _read("NOTICE")
    assert "Nous Research" in notice
    assert "MIT" in notice
    assert "https://github.com/NousResearch/hermes-agent" in notice


def test_system_prompt_identity():
    pb = _read("agent/prompt_builder.py")
    assert "You are VAEL" in pb
    assert "You are Hermes Agent, built by Nous Research" not in pb
    for rel in ("SOUL.md", "docker/SOUL.md", "hermes_cli/default_soul.py"):
        assert "You are VAEL" in _read(rel), rel


def test_no_hermes_word_in_user_strings():
    # Whole-word "Hermes" must not appear in rebranded user-facing files.
    # (Lowercase `hermes` command literals, keys, URLs and legacy-upgrade
    # tuples are intentionally out of scope for PR-1.)
    pat = re.compile(r"\bHermes\b")
    for rel in (
        "locales/en.yaml",
        "web/src/i18n/en.ts",
        "web/index.html",
        "plugins/platforms/telegram/plugin.yaml",
    ):
        text = _read(rel)
        hits = [ln for ln in text.splitlines() if pat.search(ln)]
        assert not hits, f"{rel}: {hits[:3]}"


def test_telegram_plugin_branding():
    plugin = _read("plugins/platforms/telegram/plugin.yaml")
    assert "VAEL" in plugin


def test_web_dashboard_branding():
    html = _read("web/index.html")
    assert "VAEL" in html
    assert "Hermes" not in html


def test_skill_rename_pr2():
    import subprocess

    renames = {
        "skills/autonomous-ai-agents/vael-agent/SKILL.md": "name: vael-agent",
        "skills/software-development/vael-skill-authoring/SKILL.md": (
            "name: vael-skill-authoring"
        ),
        "skills/software-development/inspecting-vael-desktop-dom/SKILL.md": (
            "name: inspecting-vael-desktop-dom"
        ),
        "optional-skills/devops/vael-s6-container-supervision/SKILL.md": (
            "name: vael-s6-container-supervision"
        ),
    }
    for rel, name_line in renames.items():
        assert (ROOT / rel).is_file(), rel
        assert name_line in _read(rel), rel
    for old in (
        "skills/autonomous-ai-agents/hermes-agent",
        "skills/software-development/hermes-agent-skill-authoring",
        "skills/software-development/inspecting-hermes-desktop-dom",
        "optional-skills/devops/hermes-s6-container-supervision",
    ):
        assert not (ROOT / old).exists(), old
    assert 'frozenset({"vael-agent"})' in _read("agent/skill_utils.py")
    assert "skill_view(name='vael-agent')" in _read("agent/prompt_builder.py")
    try:
        out = subprocess.check_output(
            ["git", "grep", "-n", "related_skills.*hermes-agent", "--", "skills", "optional-skills"],
            cwd=ROOT,
            text=True,
        )
    except subprocess.CalledProcessError:
        out = ""  # no matches — the desired state
    assert out.strip() == "", out[:500]


def test_vael_theme_pr3():
    shared = _read("apps/shared/src/theme-presets.ts")
    assert "'#D97757'" in shared or '"#D97757"' in shared
    assert "vael:" in shared or "'vael':" in shared or "vael: {" in shared
    desktop = _read("apps/desktop/src/themes/presets.ts")
    assert "DEFAULT_SKIN_NAME = 'vael'" in desktop
    assert "vaelTheme" in desktop
    web = _read("web/src/themes/presets.ts")
    assert "THEME_PRESET_PALETTES.vael" in web
    assert "Hermes Teal" not in web


def test_desktop_display_branding():
    identity = _read("apps/desktop/product-identity.cjs")
    assert "display: 'VAEL'" in identity
    # Artifact names stay stable for builds and upstream merges.
    assert "kebab: 'hermes'" in identity
    # Variants must stay distinguishable at OS level (markers invariant).
    assert "display: 'VAEL Agent'" in identity
    assert "display: 'VAEL Light'" in identity


# ---------------------------------------------------------------------------
# Website guards (W-6): the docs site is the last public-facing Hermes surface.
#
# Scope is deliberately honest rather than absolute: prose must read VAEL, but
# a few Hermes mentions are *facts* and must survive.
#   * "| Author | Hermes Agent |" rows — skill authorship from upstream SKILL.md
#     files, which this rebrand does not touch.
#   * generated skill pages/catalogs — their bodies are upstream skill text,
#     regenerated by generate-skill-docs.py on every CI run.
#   * `{#old-anchor}` heading pins — compatibility ids so links and search
#     engine anchors keep resolving after a heading was rebranded.
#   * model-family names (Hermes 4 / Hermes-4-70B) — Nous Research model names.
#   * code fences, inline code, link targets and upstream URLs — command
#     literals (`hermes chat`), paths and repo URLs that stay stable.
# ---------------------------------------------------------------------------

WEBSITE = ROOT / "website"

_FENCE_RE = re.compile(r"^\s*(`{3,}|~{3,})")
_INLINE_RE = re.compile(r"(`+)(?:(?!\1).)*\1")
_LINK_DEST_RE = re.compile(r"(\[[^\]\n]*\]\()([^)\n]*)(\))")
_URL_RE = re.compile(r"https?://\S+")
_MODEL_NAME_RE = re.compile(r"\bHermes(?=[ -]?\d)")
_HERMES_RE = re.compile(r"\bHermes\b")

_PROSE_ALLOWLIST = (
    # Skill authorship metadata (upstream SKILL.md front matter).
    re.compile(r"^\s*\|\s*Author\s*\|"),
    re.compile(r"^\s*author\s*:", re.IGNORECASE),
    # Attribution statements required by the MIT license.
    re.compile(r"based on Hermes Agent", re.IGNORECASE),
    re.compile(r"Hermes Agent by Nous Research", re.IGNORECASE),
    # ...including as Markdown link text to the upstream repository.
    re.compile(
        r"\[(?:the )?Hermes Agent\]\(https://github\.com/NousResearch/hermes-agent"
    ),
    # Compatibility anchor pins keep old inbound links resolving.
    re.compile(r"\{#[^}]*\}"),
    # Model-family table row (Nous Research's Hermes 4 lineup).
    re.compile(r"^\s*\|\s*\*\*Hermes\*\*\s*\|"),
    # The llms.txt preamble points at the upstream installer on purpose.
    re.compile(r"upstream Hermes Agent installer"),
)

# Generated from upstream skill sources (regenerated by CI).
_WEBSITE_GENERATED = (
    "docs/user-guide/skills/",
    "docs/reference/skills-catalog.md",
    "docs/reference/optional-skills-catalog.md",
    "i18n/zh-hans/",
)

# The migration page names the upstream product on purpose: its whole subject is
# moving off Hermes paths/env vars, and that is what people search for.
_WEBSITE_PROSE_ALLOWED_FILES = ("docs/getting-started/migrating-from-hermes.md",)
# Same reason for the route guard — the slug is descriptive, not branding.
_WEBSITE_ROUTE_ALLOWED = {"migrating-from-hermes.md"}


def _strip_prose(line: str) -> str:
    """Blank out code spans, link targets, URLs and model names."""
    out = _INLINE_RE.sub(lambda m: " " * len(m.group(0)), line)
    out = _LINK_DEST_RE.sub(lambda m: m.group(1) + " " * len(m.group(2)) + m.group(3), out)
    out = _URL_RE.sub(lambda m: " " * len(m.group(0)), out)
    out = _MODEL_NAME_RE.sub(lambda m: " " * len(m.group(0)), out)
    return out


def _iter_website_text_files(subdir: str, suffixes: tuple[str, ...]):
    base = WEBSITE / subdir
    for path in sorted(base.rglob("*")):
        if path.suffix.lower() not in suffixes:
            continue
        if any(part in {"node_modules", "build", ".docusaurus"} for part in path.parts):
            continue
        yield path


def _prose_hermes_hits(path: Path) -> list[str]:
    """Whole-word `Hermes` in a Markdown/MDX file's prose (not code/links)."""
    hits: list[str] = []
    text = path.read_text(encoding="utf-8", errors="replace")
    in_fence = False
    in_frontmatter = False
    for lineno, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if lineno == 1 and stripped.startswith("---"):
            in_frontmatter = True
            continue
        if in_frontmatter:
            if stripped.startswith("---"):
                in_frontmatter = False
                continue
            key = line.split(":", 1)[0].strip().lower() if ":" in line else ""
            if key in {"slug", "id"}:
                continue
            if _HERMES_RE.search(line) and not any(p.search(line) for p in _PROSE_ALLOWLIST):
                hits.append(f"{path.relative_to(ROOT)}:{lineno}: {stripped[:110]}")
            continue
        if _FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        prose = _strip_prose(line)
        if _HERMES_RE.search(prose) and not any(p.search(line) for p in _PROSE_ALLOWLIST):
            hits.append(f"{path.relative_to(ROOT)}:{lineno}: {stripped[:110]}")
    return hits


def test_website_marketing_surface_says_vael():
    """Config, React surface, sidebar and site README carry no brand leftovers."""
    # Comments in these files are allowed to explain upstream relationships;
    # executable/rendered strings are not.
    config = _read("website/docusaurus.config.ts")
    assert "title: 'VAEL Agent'" in config
    assert "title: 'Hermes Agent'" not in config
    assert "alt: 'VAEL Agent'" in config
    assert "img/vael-agent-banner.png" in config
    assert "img/hermes-agent-banner.png" not in config
    # Footer keeps the single MIT attribution line for upstream.
    assert "based on <a href=\"https://github.com/NousResearch/hermes-agent\">Hermes Agent</a>" in config

    offenders = []
    for path in _iter_website_text_files("src", (".ts", ".tsx", ".css", ".js")):
        rel = str(path.relative_to(ROOT)).replace("\\", "/")
        for lineno, line in enumerate(
            path.read_text(encoding="utf-8", errors="replace").splitlines(), 1
        ):
            if not _HERMES_RE.search(line):
                continue
            # Real community quotes live in UserStoriesCollage (unchanged, and
            # labelled as upstream in the copy).
            if rel.endswith("components/UserStoriesCollage/index.tsx"):
                continue
            if line.lstrip().startswith(("//", "*", "/*")):
                continue
            offenders.append(f"{rel}:{lineno}: {line.strip()[:110]}")
    assert not offenders, offenders[:5]

    sidebars = _read("website/sidebars.ts")
    assert "label: 'Using VAEL'" in sidebars
    # The only allowed hermes token is the descriptive migration-page slug.
    assert "hermes" not in sidebars.replace(
        "getting-started/migrating-from-hermes", ""
    )


def test_website_docs_prose_says_vael():
    """Hand-authored docs + zh-Hans mirrors have no Hermes prose left."""
    offenders: list[str] = []
    for subdir in ("docs", "i18n"):
        for path in _iter_website_text_files(subdir, (".md", ".mdx")):
            rel = str(path.relative_to(WEBSITE)).replace("\\", "/").lower()
            if any(rel.startswith(gen) for gen in _WEBSITE_GENERATED):
                continue
            if rel in _WEBSITE_PROSE_ALLOWED_FILES:
                continue
            offenders.extend(_prose_hermes_hits(path))
    assert not offenders, offenders[:5]


def test_website_generators_emit_vael():
    """The two generators whose strings reach users say VAEL."""
    for rel in (
        "website/scripts/generate-skill-docs.py",
        "website/scripts/generate-llms-txt.py",
    ):
        text = _read(rel)
        for lineno, line in enumerate(text.splitlines(), 1):
            if not _HERMES_RE.search(line):
                continue
            if line.lstrip().startswith("#"):
                continue
            if any(p.search(line) for p in _PROSE_ALLOWLIST):
                continue
            if "NousResearch/hermes-agent" in line or "hermes-agent/main" in line:
                continue  # upstream repo / installer URLs
            raise AssertionError(f"{rel}:{lineno}: {line.strip()[:110]}")


def test_website_has_no_hermes_routes():
    """No published doc path contains 'hermes' (renamed, with redirects)."""
    offenders = [
        str(path.relative_to(ROOT))
        for path in (WEBSITE / "docs").rglob("*")
        if path.is_file()
        and "hermes" in path.name.lower()
        and path.name not in _WEBSITE_ROUTE_ALLOWED
    ]
    assert not offenders, offenders

    config = _read("website/docusaurus.config.ts")
    for slug in (
        "manage-hermes-cloud-with-mcp",
        "run-hermes-with-nous-portal",
        "secure-hermes-on-a-work-machine",
        "use-mcp-with-hermes",
        "use-soul-with-hermes",
        "use-voice-mode-with-hermes",
    ):
        assert f"from: '/guides/{slug}'" in config, slug
        assert f"to: '/guides/{slug.replace('hermes', 'vael')}'" in config, slug


def test_website_brand_assets_exist():
    """The navbar mark, favicon and OG image are the VAEL ones."""
    for rel in (
        "website/static/img/vael-mark.svg",
        "website/static/img/vael-mark-dark.svg",
        "website/static/img/favicon.svg",
        "website/static/img/vael-agent-banner.png",
    ):
        assert (ROOT / rel).is_file(), rel
    assert "#D97757" in _read("website/static/img/favicon.svg")


# ---------------------------------------------------------------------------
# IR-5/IR-6: model-facing content guards. The model reads skill bodies, tool
# descriptions and the assembled system prompt; those must say VAEL.
# Facts that must survive (same allowlist philosophy as the website guards):
#   * `author:` rows — upstream skill authorship, not branding.
#   * upstream URLs (github.com/NousResearch/hermes-agent, *.nousresearch.com).
#   * R-7 compat paths/env (`~/.hermes`, `$HERMES_HOME`, `HERMES_*`) and
#     infra artifacts joined to path characters (`/opt/hermes/...`,
#     `main-hermes/run`, `hermes.service`).
#   * `metadata.hermes.*` where it documents the accepted legacy frontmatter
#     key (dual-read: `metadata.vael` primary, `metadata.hermes` fallback).
#   * code spans/fences (command literals work via the `hermes` alias) and
#     Nous Research model names (`Hermes 4`, `Hermes-4-70B`).
# ---------------------------------------------------------------------------

import ast

_SKILL_BODY_ALLOWLIST = (
    re.compile(r"^\s*author\s*:", re.IGNORECASE),
    re.compile(r"https?://\S*"),
    re.compile(r"NousResearch/hermes-agent"),
    re.compile(r"hermes-agent\.nousresearch\.com"),
    re.compile(r"~\/\.hermes|\$HERMES_HOME|\bHERMES_[A-Z_]+|\.hermes\/|\/opt\/hermes\/"),
    re.compile(r"metadata\.hermes\b"),
    re.compile(r"\bHermes(?=[ -]?\d)"),
)

_INLINE_CODE_RE = re.compile(r"(`+)(?:(?!\1).)*\1")
_FENCE_RE = re.compile(r"^\s*(`{3,}|~{3,})")


def _skill_prose_hits(path):
    """Whole-word Hermes in a SKILL.md's prose (not code/URLs/attribution)."""
    hits = []
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return hits
    in_fence = False
    for lineno, line in enumerate(text.splitlines(), 1):
        if _FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        prose = _INLINE_CODE_RE.sub(" ", line)
        if _HERMES_RE.search(prose) and not any(p.search(line) for p in _SKILL_BODY_ALLOWLIST):
            hits.append(f"{path.relative_to(ROOT)}:{lineno}: {line.strip()[:110]}")
    return hits


def test_vael_skill_bodies_say_vael():
    """Renamed (vael-*) skills read VAEL in prose (IR-5)."""
    offenders = []
    for base in ("skills", "optional-skills"):
        root = ROOT / base
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("SKILL.md")):
            if "vael-" not in str(path):
                continue
            offenders.extend(_skill_prose_hits(path))
    assert not offenders, offenders[:5]


def test_tool_schema_descriptions_say_vael():
    """Model-facing tool (schema description=) strings carry no Hermes (IR-5)."""
    offenders = []
    for path in sorted((ROOT / "tools").glob("*.py")):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except (SyntaxError, OSError):
            continue
        for node in ast.walk(tree):
            values = []
            if isinstance(node, ast.keyword) and node.arg == "description":
                values = [node.value]
            elif isinstance(node, ast.Dict):
                values = [
                    v for k, v in zip(node.keys, node.values)
                    if isinstance(k, ast.Constant) and k.value == "description"
                ]
            for value in values:
                if (
                    isinstance(value, ast.Constant)
                    and isinstance(value.value, str)
                    and _HERMES_RE.search(value.value)
                ):
                    offenders.append(f"{path.name}:{value.lineno}")
    assert not offenders, offenders[:5]


def test_cli_primary_is_vael():
    """`vael` is the primary entry point; `hermes` is a deprecated alias (IR-4)."""
    scripts = _read("pyproject.toml")
    vael = re.search(r'^\s*vael\s*=\s*"([^"]+)"', scripts, re.MULTILINE)
    hermes = re.search(r'^\s*hermes\s*=\s*"([^"]+)"', scripts, re.MULTILINE)
    assert vael and hermes, "both entry points must exist"
    assert vael.group(1) == hermes.group(1), "alias must run the same CLI"
    main = _read("hermes_cli/main.py")
    assert "_warn_if_deprecated_hermes_alias" in main


def test_no_old_top_module_imports():
    """No code imports the pre-IR2 top-level `hermes_*` modules (IR-6).

    The `hermes_cli` package is real and stays; only the renamed top-level
    modules (every `vael_*.py` at the repo root, mapped back) are forbidden.
    AST-based so comments, strings and docstrings never trip it.
    """
    forbidden = {"hermes_" + p.stem[len("vael_"):] for p in ROOT.glob("vael_*.py")}
    assert forbidden, "expected renamed vael_*.py modules at the repo root"
    offenders = []
    dirs = (
        "tests",
        "tools",
        "agent",
        "gateway",
        "hermes_cli",
        "tui_gateway",
        "cron",
        "plugins",
        "acp_adapter",
    )
    files = [p for p in ROOT.glob("*.py")]
    for d in dirs:
        root = ROOT / d
        if root.is_dir():
            files.extend(root.rglob("*.py"))
    import_re = re.compile(r"(?m)^\s*(?:from|import)\s+hermes_(?!cli\b)")
    for path in sorted(set(files)):
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        if not import_re.search(text):
            continue  # cheap pre-filter; AST parse only on candidates
        try:
            tree = ast.parse(text)
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            names = []
            if isinstance(node, ast.Import):
                names = [(a.name or "").split(".")[0] for a in node.names]
            elif isinstance(node, ast.ImportFrom) and node.module:
                names = [node.module.split(".")[0]]
            for name in names:
                if name in forbidden:
                    offenders.append(f"{path.relative_to(ROOT)}:{node.lineno}: {name}")
    assert not offenders, offenders[:5]


if __name__ == "__main__":
    for name, fn in sorted(
        [(k, v) for k, v in globals().items() if k.startswith("test_")],
    ):
        fn()
        print(f"PASS {name}")
    print("VAEL brand guards: ALL GREEN")
