#!/usr/bin/env python3
"""One-shot, idempotent prose rebrand for the docs site: Hermes -> VAEL.

Why this exists
---------------
The rebrand (see REBRANDING.md) renames the *product surface* only: display
name, marketing copy, headings, meta tags. It deliberately does not rename the
CLI command literals (``hermes chat``), config paths (``~/.hermes``), env vars
(``HERMES_*``), upstream repo URLs, or code identifiers such as
``Hermes-Session-Token`` — those are behavioural contracts that stay stable for
upstream merges (R-7 kept the call sites untouched).

So a blind find/replace is wrong. This script walks only the *prose* of the
docs (Markdown/MDX), leaving fenced code blocks, inline code spans, link
destinations, URLs and HTML attribute values untouched, and applies an explicit
rule list. Attribution lines ("Author | Hermes Agent", "based on Hermes Agent")
are preserved verbatim.

Generated pages are skipped on purpose: ``website/docs/user-guide/skills/**``,
``website/docs/reference/{,optional-}skills-catalog.md`` and their zh-Hans
twins are produced by ``website/scripts/generate-skill-docs.py``. CI
(``docs-site-checks.yml``) regenerates them and fails if the committed copies
differ, so those strings must be fixed in the generator instead.

Usage
-----
    python3 website/scripts/rebrand-hermes-to-vael.py            # dry run
    python3 website/scripts/rebrand-hermes-to-vael.py --write    # apply

Stdlib only. Idempotent: running it twice reports no changes the second time.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DOC_SUFFIXES = {".md", ".mdx"}

# Doc pages whose route contained "hermes". Renamed with `git mv` (EN + zh-Hans
# mirrors); this table drives `--rewrite-guide-refs`, which repoints every
# relative Markdown link, sidebar id and generator list at the new slug.
GUIDE_RENAMES = {
    "manage-hermes-cloud-with-mcp": "manage-vael-cloud-with-mcp",
    "run-hermes-with-nous-portal": "run-vael-with-nous-portal",
    "secure-hermes-on-a-work-machine": "secure-vael-on-a-work-machine",
    "use-mcp-with-hermes": "use-mcp-with-vael",
    "use-soul-with-hermes": "use-soul-with-vael",
    "use-voice-mode-with-hermes": "use-voice-mode-with-vael",
}

# Never rewrite these:
#   * this script — GUIDE_RENAMES deliberately spells the old slugs;
#   * docusaurus.config.ts — its `from:` entries *are* the old slugs (client
#     redirects); rewriting them would delete the redirects.
REF_SKIP_NAMES = {"rebrand-hermes-to-vael.py", "docusaurus.config.ts"}

# Generated by generate-skill-docs.py; edited through the generator, not here.
GENERATED_PATTERNS = (
    "docs/user-guide/skills/",
    "docs/reference/skills-catalog.md",
    "docs/reference/optional-skills-catalog.md",
    "i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-guide/skills/",
    "i18n/zh-Hans/docusaurus-plugin-content-docs/current/reference/skills-catalog.md",
    "i18n/zh-Hans/docusaurus-plugin-content-docs/current/reference/optional-skills-catalog.md",
)

# Lines that carry attribution and must keep the upstream name.
#   | Author | Hermes Agent |
#   author: Hermes Agent
#   ... based on Hermes Agent (MIT) ...
ATTRIBUTION_RES = (
    re.compile(r"^\s*(?:\|\s*Author\s*\||author\s*:)", re.IGNORECASE),
    re.compile(r"based on Hermes Agent", re.IGNORECASE),
    re.compile(r"Hermes Agent by Nous Research", re.IGNORECASE),
)

# Front matter keys whose values are routes/ids, never copy.
PROTECTED_FRONTMATTER_KEYS = {
    "slug",
    "id",
    "image",
    "editurl",
    "pagination_next",
    "pagination_prev",
}

# ---------------------------------------------------------------------------
# Replacement rules (ordered; each applies to prose only)
# ---------------------------------------------------------------------------

# Hyphenated *prose* compounds that take the brand name. Wire-protocol and
# artifact identifiers are deliberately absent: `X-Hermes-Session-Id`,
# `Hermes-Setup.exe`, `Hermes-Monitor/1.0`, `Hermes-Agent/<version>` and
# `Hermes-Meeting-Pipeline-Policy` are contracts, not marketing copy.
HYPHENATED = (
    "managed",
    "specific",
    "side",
    "native",
    "synced",
    "prefixed",
    "known",
    "compatible",
    "canonical",
    "aware",
    "added",
    "owned",
    "internal",
    "style",
    "flavored",
    "only",
    "wide",
    "era",
    "authored",
    "initiated",
    "generated",
    "provided",
    "sent",
    "tool",
    "tools",
    "on",
)

RULES: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"\bHermes Agent\b"), "VAEL Agent"),
    (re.compile(r"\bHermes agent\b"), "VAEL Agent"),
    (re.compile(r"\bHermes[’]s\b"), "VAEL’s"),
    (re.compile(r"\bHermes's\b"), "VAEL's"),
    # Possessive without a second s ("Hermes' resolver") is singular here.
    (re.compile(r"\bHermes[’]"), "VAEL’s"),
    (re.compile(r"\bHermes'"), "VAEL's"),
    # Hyphenated prose compounds keep their suffix and casing ("Hermes-Managed").
    (re.compile(r"\bHermes-((?i:" + "|".join(HYPHENATED) + r"))\b"), r"VAEL-\1"),
    # Standalone brand word. The negative lookahead keeps identifiers
    # (HermesCLI, HermesPlugin, Hermes_Gateway) and wire-protocol header names
    # (Hermes-Session-Token) intact.
    (re.compile(r"\bHermes\b(?![A-Za-z0-9_-])"), "VAEL"),
]

# Lowercase prose product references. Command literals (`hermes chat`),
# paths (~/.hermes), package names (@hermes/plugin-sdk) and upstream URLs are
# NOT here on purpose — see the module docstring.
LOWERCASE_RULES: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"\bexposes hermes\b"), "exposes VAEL"),
    (re.compile(r"\bMultiple hermes processes\b"), "Multiple VAEL processes"),
    (re.compile(r"\bthe hermes codebase\b"), "the VAEL codebase"),
    (re.compile(r"\bWhen hermes runs\b"), "When VAEL runs"),
    (re.compile(r"\bcore hermes dependencies\b"), "core VAEL dependencies"),
    (re.compile(r"\byour hermes config\b"), "your VAEL config"),
]

# ---------------------------------------------------------------------------
# Prose extraction
# ---------------------------------------------------------------------------

FENCE_RE = re.compile(r"^\s*(`{3,}|~{3,})")
INLINE_RE = re.compile(r"(`+)(?:(?!\1).)*\1")
HTML_ATTR_RE = re.compile(
    r"""\b(?:href|src|srcSet|srcset|url|to|image|logo)\s*=\s*["'][^"']*["']"""
)
URL_RE = re.compile(r"https?://\S+")
MD_LINK_RE = re.compile(r"(\[[^\]\n]*\]\()([^)\n]*)(\))")
# Model-family names are product names of their own (Nous Research's Hermes 4
# lineup). Renaming them would be a false claim.
MODEL_NAME_RE = re.compile(r"\bHermes(?=[ -]?\d)")


def _shield(line: str) -> str:
    """Blank out spans that must survive verbatim, preserving length/offsets."""
    out = INLINE_RE.sub(lambda m: "\x00" * len(m.group(0)), line)
    out = HTML_ATTR_RE.sub(lambda m: "\x00" * len(m.group(0)), out)
    out = MD_LINK_RE.sub(
        lambda m: m.group(1) + "\x00" * len(m.group(2)) + m.group(3), out
    )
    out = URL_RE.sub(lambda m: "\x00" * len(m.group(0)), out)
    out = MODEL_NAME_RE.sub(lambda m: "\x00" * len(m.group(0)), out)
    return out


def _apply(text: str) -> tuple[str, int]:
    total = 0
    for pattern, repl in (*RULES, *LOWERCASE_RULES):
        text, n = pattern.subn(repl, text)
        total += n
    return (text, total)


def transform_line(line: str) -> tuple[str, int]:
    """Rebrand one line of prose. Returns (new_line, replacement_count)."""
    shielded = _shield(line)
    result: list[str] = []
    count = 0
    for match in re.finditer(r"\x00+|[^\x00]+", shielded):
        if match.group(0).startswith("\x00"):
            result.append(line[match.start() : match.end()])
            continue
        live = line[match.start() : match.end()]
        new_live, n = _apply(live)
        result.append(new_live)
        count += n
    return ("".join(result), count)


def _protected_line(line: str) -> bool:
    return any(pat.search(line) for pat in ATTRIBUTION_RES)


def skip_file(rel: str) -> bool:
    rel = rel.replace("\\", "/")
    if rel in PROSE_SKIP_FILES:
        return True
    return any(pat in rel for pat in GENERATED_PATTERNS)


def process_file(path: Path) -> tuple[str, int]:
    """Return (new_text, replacement_count) for one file."""
    original = path.read_text(encoding="utf-8")
    lines = original.splitlines(keepends=True)
    in_fence = False
    in_frontmatter = False
    total = 0
    out: list[str] = []
    for index, line in enumerate(lines):
        bare = line.strip()
        if index == 0 and bare.startswith("---"):
            in_frontmatter = True
            out.append(line)
            continue
        if in_frontmatter:
            if bare.startswith("---"):
                in_frontmatter = False
                out.append(line)
                continue
            key = line.split(":", 1)[0].strip().lower() if ":" in line else ""
            if key in PROTECTED_FRONTMATTER_KEYS:
                out.append(line)
                continue
            new_line, count = transform_line(line)
            total += count
            out.append(new_line)
            continue
        if FENCE_RE.match(line):
            in_fence = not in_fence
            out.append(line)
            continue
        if in_fence or _protected_line(line):
            out.append(line)
            continue
        new_line, count = transform_line(line)
        total += count
        out.append(new_line)
    return ("".join(out), total)


def iter_targets(root: Path) -> list[Path]:
    paths: list[Path] = []
    for path in sorted(root.rglob("*")):
        if path.suffix.lower() not in DOC_SUFFIXES:
            continue
        if any(part in {"node_modules", "build", ".docusaurus"} for part in path.parts):
            continue
        if skip_file(str(path.relative_to(root))):
            continue
        paths.append(path)
    return paths


# Files that name the upstream project on purpose (they document the
# relationship, and the website guards allow-list them).
PROSE_SKIP_FILES = {
    "README.md",
    "docs/getting-started/migrating-from-hermes.md",
}

REF_SUFFIXES = {".md", ".mdx", ".ts", ".tsx", ".js", ".mjs", ".py", ".json"}


def rewrite_guide_references(root: Path, write: bool) -> int:
    """Repoint references at the renamed guide slugs (see GUIDE_RENAMES)."""
    changed = 0
    for path in sorted(root.rglob("*")):
        if path.suffix.lower() not in REF_SUFFIXES:
            continue
        if any(part in {"node_modules", "build", ".docusaurus", ".git"} for part in path.parts):
            continue
        if path.name in REF_SKIP_NAMES:
            continue
        text = path.read_text(encoding="utf-8", errors="strict")
        new = text
        for old, repl in GUIDE_RENAMES.items():
            new = new.replace(old, repl)
        if new == text:
            continue
        changed += 1
        if write:
            path.write_text(new, encoding="utf-8")
        print(f"  refs {'written' if write else 'would change'}: {path}")
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--root", type=Path, default=Path(__file__).resolve().parent.parent
    )
    parser.add_argument(
        "--write", action="store_true", help="apply changes (default: dry run)"
    )
    parser.add_argument(
        "--rewrite-guide-refs",
        action="store_true",
        help="only repoint references at the renamed guide slugs",
    )
    args = parser.parse_args(argv)

    if args.rewrite_guide_refs:
        # Links to those slugs live under website/ only; scanning the repo root
        # would crawl .venv for nothing.
        changed = rewrite_guide_references(args.root, args.write)
        print(f"{'rewrote' if args.write else 'would rewrite'} {changed} file(s)")
        return 0

    targets = iter_targets(args.root)
    changed: list[tuple[Path, int]] = []
    for path in targets:
        new_text, count = process_file(path)
        if not count:
            continue
        changed.append((path, count))
        if args.write:
            path.write_text(new_text, encoding="utf-8")

    total = sum(count for _, count in changed)
    for path, count in changed:
        try:
            rel = path.relative_to(args.root)
        except ValueError:
            rel = path
        print(f"{count:5d}  {rel}")
    verb = "wrote" if args.write else "would change"
    print(
        f"\n{verb} {len(changed)} file(s), {total} replacement(s) "
        f"across {len(targets)} scanned file(s)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
